### ISSUE TITLE
[Failure] 58 3 | add_comp_edu: add_comp_edu computes correct scores

### ISSUE THREAD

**Issue by lanawwas** [impact-initiatives-hppu/humind#438] opened 2024-07-15 07:16 UTC
── Failure ('test-add_comp_edu.R:58:3'): Function computes correct scores ──────
result$comp_edu_in_acute_need not equal to c(0, 1, 1, 1, 0, 1).
4/6 mismatches (average diff: 1)
[2] 0 - 1 == -1
[3] 0 - 1 == -1
[4] 0 - 1 == -1
[6] 0 - 1 == -1

Test scenario 

```R
# 4. Test correctness of computed scores
test_that("Function computes correct scores", {
  result <- add_comp_edu(dummy_data)

  # Check comp_edu_score_disrupted
  expect_equal(result$comp_edu_score_disrupted, c(1, 3, 4, 3, 1, 2))

  # Check comp_edu_score_attendance
  expect_equal(result$comp_edu_score_attendance, c(1, 4, 1, 4, 1, 4))

  # Check comp_edu_score
  expect_equal(result$comp_edu_score, c(1, 4, 4, 4, 1, 4))

  # Check comp_edu_in_need
  expect_equal(result$comp_edu_in_need, c(0, 1, 1, 1, 0, 1))

  # Check comp_edu_in_acute_need
  expect_equal(result$comp_edu_in_acute_need, c(0, 1, 1, 1, 0, 1))
})
```

**Comment by gnoblet** [comment] 2024-07-24 11:05
@lanawwas  i cannot reproduce this error, it's probably been fixed with commit 80268c63dea57f774d7a1d3d8f6013d0d4e7fb9a

closing for now

**Closed as completed by gnoblet** 2024-07-24 11:05 UTC
Labels: wontfix
